### ISSUE TITLE
Create UUID Lookup Tool

### ISSUE THREAD

**Issue by joeponcy** [Innovate-Inc/EMEMetadataToolKit#10]

**Comment by joeponcy** [comment]
Add Lookup button to find UUID
Default search by title from EDG Rest service
Include option for advanced filters
![image](https://cloud.githubusercontent.com/assets/5324141/21406070/8eae0774-c77e-11e6-91f8-96c17525b601.png)

**Comment by torrin47** [comment]
General Documentation for REST API:
https://edg.epa.gov/metadata/catalog/components/components.page
Example search syntax for basic JSON response:
https://edg.epa.gov/metadata/rest/find/document?f=json&searchText=title:"EnviroAtlas - HU12_polygon"

**Comment by torrin47** [comment]
This issue was moved to USEPA/EPA-Metadata-Editor-5#5

**Comment by joeponcy** [comment]
Issue transferred to the [USEPA Repo](https://github.com/USEPA/EPA-Metadata-Editor-5) using https://github.com/google/github-issue-mover.
