### ISSUE TITLE
Does Esri offer any way to eliminate the "validate" button?

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EMEMetadataToolKit#105]
We wrote into the user guide that this button really provides no value and is more confusing than anything else. Ana wondered whether the button could be eliminated...

![image](https://cloud.githubusercontent.com/assets/2127036/21441457/24050dee-c866-11e6-86a7-6aaf6806624b.png)

**Comment by joeponcy** [comment]
I don't believe we have any way to access those controls. We may have to reach out to Esri for this one.

Sent from my Windows 10 phone

From: Torrin Hultgren
Sent: Thursday, December 22, 2016 1:48 PM
To: Innovate-Inc/EMEMetadataToolKit
Cc: Subscribed
Subject: [Innovate-Inc/EMEMetadataToolKit] Does Esri offer any way toeliminate the "validate" button? (#105)

We wrote into the user guide that this button really provides no value and is more confusing than anything else. Ana wondered whether the button could be eliminated...

**Comment by torrin47** [comment]
Going to open ticket with Esri to confirm.

**Comment by torrin47** [comment]
Aleta said that this is completely impossible and the guy who'd know anything about it is no longer at Esri - in that order.  Sigh.  Closing ticket.
