### ISSUE TITLE
Title validation

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EMEMetadataToolKit#11]
I suspect that there are few to no cases where a one-word title would be acceptable or appropriate - more often a one-word title is derived from the file name (or database tablename) and indicates that the user hasn't thought through a real title.  Unless we can brainstorm a scenario in which a single word title would be applicable, we should have a validation rule not permitting single-word titles.

**Comment by joeponcy** [comment]
Validation error should be more general to discourage users from bypassing the validator.
