### ISSUE TITLE
Add Autocomplete Input Control to Program Codes

### ISSUE THREAD

**Issue by wurlibus** [Innovate-Inc/EMEMetadataToolKit#110]
- [ ] Create custom TextBox control with auto-complete behavior.
- [ ] Use two-way binding between checkbox and input box.
- [ ] Choosing the selected value will mark corresponding checkbox.
- [ ] Clicking a checkbox will update the input box.

**Comment by torrin47** [comment]
This issue was moved to USEPA/EPA-Metadata-Editor-5#14

**Comment by torrin47** [comment]
This issue was moved to USEPA/EPA-Metadata-Editor-5#15

**Comment by joeponcy** [comment]
Issue transferred to the [USEPA Repo](https://github.com/USEPA/EPA-Metadata-Editor-5) using https://github.com/google/github-issue-mover.
