### ISSUE TITLE
Create UI and thesaurus citation for selection of place keywords

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EMEMetadataToolKit#13]
Data.gov links to http://www.geonames.org/ for official placenames. EPA taxonomies registry also includes a shorter list: https://ofmpub.epa.gov/sor_internet/registry/termreg/searchandretrieve/taxonomies/search.do

Seems like a multiselect is the best option, but still need a finite domain to work with.

**Comment by joeponcy** [comment]
Let's further refine this issue.

**Comment by torrin47** [comment]
On the surface, this ticket is really about populating the optional Thesaurus Citation section for any keyword block where we are presenting the users with a checklist to choose from.  The citation wouldn't be editable to the user, but would populate on pageload. I'd like for this to be a full, rich citation, but at the moment I'm really dissatisfied with what's actually available to us, so a simple title might have to suffice. In a perfect service oriented world, we'd be able to present users with a choice of thesaurus, and depending on what they choose, our code would go fetch the valid values in real time and present them to the end users. This isn't realistic today. So for now, just ensuring that the citation contains the most basic values is sufficient.
