### ISSUE TITLE
Add expandable guidance to elements within Metadata Editor

### ISSUE THREAD

**Issue by joeponcy** [Innovate-Inc/EMEMetadataToolKit#132]
Include text from EME 5.0 Metadata Style Guide
- create styleguide xml?
- link to styleguide web page?

**Comment by joeponcy** [comment]
Issue #138 fulfills the immediate need for enhanced guidance. Would still be nice to have in-context guidance such as style guide pop-ups or collapsible info controls.

Main issue is maintaining documents in multiple places. Is it possible to link the pop-up content to a wiki page?

**Comment by torrin47** [comment]
Weblinks seem to be serving users well, let's leave this in icebox until if/when users complain.

**Comment by torrin47** [comment]
This issue was moved to USEPA/EPA-Metadata-Editor-5#17

**Comment by joeponcy** [comment]
Issue transferred to the [USEPA Repo](https://github.com/USEPA/EPA-Metadata-Editor-5) using https://github.com/google/github-issue-mover.
