### ISSUE TITLE
Create contacts batch editor

### ISSUE THREAD

**Issue by joeponcy** [Innovate-Inc/EMEMetadataToolKit#133]

**Comment by joeponcy** [comment]
Find and replace contact info in local document

**Comment by torrin47** [comment]
This issue was moved to USEPA/EPA-Metadata-Editor-5#22

**Comment by joeponcy** [comment]
Issue transferred to the [USEPA Repo](https://github.com/USEPA/EPA-Metadata-Editor-5) using https://github.com/google/github-issue-mover.
