### ISSUE TITLE
Turn off visibility of EPA Data License if node already exists

### ISSUE THREAD

**Issue by joeponcy** [Innovate-Inc/EMEMetadataToolKit#144]
See issue #143 
Could not come up with a satisfactory solution within the time constraint. This will have to be an enhancement to add at a later date.

**Comment by torrin47** [comment]
This issue was moved to USEPA/EPA-Metadata-Editor-5#18

**Comment by joeponcy** [comment]
Issue transferred to the [USEPA Repo](https://github.com/USEPA/EPA-Metadata-Editor-5) using https://github.com/google/github-issue-mover.
