### ISSUE TITLE
Clear URL validation error for EPA Data License

### ISSUE THREAD

**Issue by joeponcy** [Innovate-Inc/EMEMetadataToolKit#145]
Currently the error will clear if you navigate away from the Constraints section.
So far all attempts to refresh the control at load have had no effect.
Since this element has been changed to read-only I am not sure if a Focus() is triggering properly.

**Comment by torrin47** [comment]
This issue was moved to USEPA/EPA-Metadata-Editor-5#19

**Comment by joeponcy** [comment]
Issue transferred to the [USEPA Repo](https://github.com/USEPA/EPA-Metadata-Editor-5) using https://github.com/google/github-issue-mover.
