### ISSUE TITLE
Investigate issue with Python versions

### ISSUE THREAD

**Issue by joeponcy** [Innovate-Inc/EMEMetadataToolKit#151]
It appears that installing stand-alone Python after installing ArcGIS will break the python tools in the EME toolbox.
Investigate the problem. May be a simple registry check that could be added to the installer.

**Comment by torrin47** [comment]
This issue was moved to USEPA/EPA-Metadata-Editor-5#20

**Comment by joeponcy** [comment]
Issue transferred to the [USEPA Repo](https://github.com/USEPA/EPA-Metadata-Editor-5) using https://github.com/google/github-issue-mover.
