### ISSUE TITLE
Upgrade from FGDC to ArcGIS does not pull Summary

### ISSUE THREAD

**Issue by jlholder** [Innovate-Inc/EMEMetadataToolKit#152]
Summary (purpose) from older FGDC versions is not coming across in the upgrade.

**Comment by torrin47** [comment]
This is actually a feature, not a bug.  

Per:
https://github.com/USEPA/EPA-Metadata-Editor-5/wiki/EME-5.0-Validation-Tips

> Note that legacy "Purpose" field has been moved to "Supplemental Information" element because of ambiguous use of the new "summary" field.

Esri decided to repurpose "purpose" as this vague summary element for us in ArcGISOnline, and rarely, if ever, is the text written for "purpose" from a CSDGM document appropriate, so we move it elsewhere.
