### ISSUE TITLE
Formatting for UUID for EDG??

### ISSUE THREAD

**Issue by jlholder** [Innovate-Inc/EMEMetadataToolKit#155]
May also be an issue with ArcGIS metadata format of UUID. Does EDG require with or without {} brackets?

Old metadata format places brackets around UUID, new version does not.
![image](https://cloud.githubusercontent.com/assets/17882165/26252877/74c67d70-3c7f-11e7-94da-a0feed542ddf.png)

Which do we need? And does EME 5.0 need to be updated to add brackets?

**Comment by torrin47** [comment]
The answer is it doesn't matter - EDG is fine with it either way, will treat a UUID with curly braces as equal to the same UUID without curly braces.  EME 3.2.1 followed the internal EDG convention, which was to include curly braces, but Esri baked a UUID generator into ArcCatalog that did not include curly braces, and this convention seems slightly more universal, so we included it as-is in EME 5.0.

**Comment by dspinosa** [comment]
@torrin47   This does not seem to work:
-  https://edg.epa.gov/metadata/catalog/search/resource/details.page?uuid=CD8CC8C4-A92C-404A-8898-7A7F157553ED

But this works:
- https://edg.epa.gov/metadata/catalog/search/resource/details.page?uuid={CD8CC8C4-A92C-404A-8898-7A7F157553ED}

**Comment by torrin47** [comment]
Ok, fair, it's not perfectly interchangeable - and goes to show that for embedding purposes, listing the UUID without curly braces is a better solution.  Note that in the metadata, the curly braces are explicitly included. If no curly braces were embedded in the document, both links would work.
