### ISSUE TITLE
Add timestamp check to contacts fetch

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EMEMetadataToolKit#158]
The totally sweet live download of contacts from the EDG server does cause a slight lag in viewing the contacts manager.  Once a session this isn't bad, but it starts getting annoying if someone goes in and out of the pane. Could we add a check to examine the timestamp of the cached file, and if it's been updated within the last 24 hours, to use the local copy and not fetch from online?

Also, I believe we discussed making the URL at which the contacts are fetched configurable - this would address the ability to "customize" the list of contacts for a different organization. This could serve both EPA and external user communities. Wonder if it would also mean we'd need to change the naming convention of "EPA Contact" to something more generic?

**Comment by joeponcy** [comment]
The interface where the user chooses a custom URL can also require a source name.

I'm thinking these customization options will be accessible through the EME Db Manager. I'm also toying with the possibility of configuring the agency branding through a similar interface.
