### ISSUE TITLE
Streamline editing of constraints

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EMEMetadataToolKit#16]
Seems highly desirable to have a single-button option for "public" records that populates the license and use constraint.
Also need to make validation rule requiring license and use constraint per technical spec - should confirm license is URL.

**Comment by joeponcy** [comment]
![image](https://cloud.githubusercontent.com/assets/5324141/21246512/236c9f38-c2de-11e6-92b0-18e06ae99e49.png)

**Comment by joeponcy** [comment]
![image](https://cloud.githubusercontent.com/assets/5324141/21246601/9d44b8cc-c2de-11e6-99e0-4f7fb84879a1.png)

Can we do something with coded values?

**Comment by joeponcy** [comment]
Re-work validation to test for URL in othConsts
