### ISSUE TITLE
The download page only downloads the manager not the editor

### ISSUE THREAD

**Issue by dbriggsUSGS** [Innovate-Inc/EMEMetadataToolKit#165]
When I download the version for 10.5 - I only get the EPA manager, not the editor.
Do you have another link?
Deb

**Comment by joeponcy** [comment]
The Metadata Editor is not a stand-alone application. You need to access it through ArcCatalog.

Once installed you will find the "EPA Metadata Specification..." in ArcCatalog Options >> Metadata. Selecting this stylesheet will enable the EME functionality in the normal ArcCatalog metadata editing interface.

**Comment by torrin47** [comment]
This issue was moved to USEPA/EPA-Metadata-Editor-5#4

**Comment by joeponcy** [comment]
Issue transferred to the [USEPA Repo](https://github.com/USEPA/EPA-Metadata-Editor-5) using https://github.com/google/github-issue-mover.
