### ISSUE TITLE
Streamline authoring of Distribution URL.  

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EMEMetadataToolKit#21]
The whole section is intimidating and confusing.  The following checklist attempts to clarify/refine the Digital Transfer Options block, and the Online Resource subblock.
- [x] Hide Units of Distribution and Transfer Size in a collapsible section called "Download Details" that is closed by default
- [ ] Have Protocol automatically reflect the portion of "Linkage" that precedes ".//" so if the URL begins http://, https://, or ftp://, Protocol would show http, https, or ftp, respectively, without a user needing to populate it.
- [x] Reorder fields so that Protocol and Profile come after Name, Description, and Function.

- [ ] The connection protocol to be used. When applicable, use the identifier values in this codelist hosted by Open Source Geospatial Foundation. (https://geo-ide.noaa.gov/wiki/index.php?title=CI_OnlineResource)

https://github.com/OSGeo/Cat-Interop/blob/master/LinkPropertyLookupTable.csv

**Comment by joeponcy** [comment]
Let's further refine this issue.
