### ISSUE TITLE
Ensure that the metadata date stamp is updated whenever an edit is saved

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EMEMetadataToolKit#22]
Why is this not the default esri behavior?

**Comment by joeponcy** [comment]
Auto-update date stamp when document is opened. If edit is cancelled nothing is saved.

**Comment by joeponcy** [comment]
![image](https://cloud.githubusercontent.com/assets/5324141/18973119/e4fa6d9e-8650-11e6-90c2-3fbfd90037f2.png)

**Comment by dspinosa** [comment]
https://www.epa.gov/geospatial/draft-epa-metadata-technical-specification#metadata-date-stamp
