### ISSUE TITLE
Review Mandatory fields in Tech spec, ensure all are being enforced.

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EMEMetadataToolKit#23]
When we're nearing completion.

**Comment by joeponcy** [comment]
- [ ] **Title** 
- [ ] **Description**
- [ ] **Keywords (_General, ISO, Place, EPA, Program Code_)**
- [ ] **Tags (_EPA Org_)**
- [ ] **Last Update**
- [ ] **Publisher (_Name, Organization, Email_)**
- [ ] **UUID**
- [ ] **Access Level**
- [ ] **Data License**
- [ ] **Temporal Extent**
- [ ] **Metadata Date Stamp**
- [ ] **Metadata Responsible Party**
