### ISSUE TITLE
Create an installer to add custom metadata config files to the appropriate ArcGIS folders

### ISSUE THREAD

**Issue by joeponcy** [Innovate-Inc/EMEMetadataToolKit#32]
bin for .dlls
Metadata\Config for style configuration file
Metadata\Stylesheets for XSLT stylesheet
Metadata\Translator for custom translator config
Metadata\Translator\Transforms for custom XSLT transformations

**Comment by dspinosa** [comment]
Need to add path for the MetadataTool Kit XML data tables.  Follow the pattern used for EME 3 and 4 x.
