### ISSUE TITLE
Getting more done in GitHub with ZenHub

### ISSUE THREAD

**Issue by joeponcy** [Innovate-Inc/EMEMetadataToolKit#33]
Hola! @joeponcy has created a [ZenHub](http://www.zenhub.io) account for the **Innovate-Inc** organization. ZenHub is the only project management tool integrated natively in GitHub – created specifically for fast-moving, software-driven teams.

----

#### How do I use ZenHub?

To get set up with ZenHub, all you have to do is **[download the browser extension](https://www.zenhub.io?utm_source=ZHOnboarding)** and log in with your GitHub account. Once you do, you’ll get access to ZenHub’s complete feature-set immediately.

#### What can ZenHub do?

ZenHub adds a series of enhancements directly inside the GitHub UI:

- Real-time, customizable task boards for GitHub issues;
- Multi-Repository burndown charts, estimates, and velocity tracking based on GitHub Milestones;
- Personal to-do lists and task prioritization;
- Time-saving shortcuts – like a quick repo switcher, a “Move issue” button, and much more.

### [Add ZenHub to GitHub](https://www.zenhub.io?utm_source=ZHOnboarding)

_Still curious? See [more ZenHub features](https://www.zenhub.io/features?utm_source=ZHOnboarding) or read [user reviews](https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd/reviews). This issue was written by your friendly ZenHub bot, posted by request from @joeponcy._

![ZenHub Board](https://cloud.githubusercontent.com/assets/8771909/11153956/233ac4a8-89f1-11e5-94b1-1569d3f38b4d.png)

**Comment by torrin47** [comment]
Very cool, but wow, are all of those issues actually in progress
simultaneously?

On Fri, Jun 10, 2016 at 10:07 AM, Joseph Poncy <notifications@github.com>
wrote:

> Hola! @joeponcy <https://github.com/joeponcy> has created a ZenHub
> <http://www.zenhub.io> account for the *Innovate-Inc* organization.
> ZenHub is the only project management tool integrated natively in GitHub –
> created specifically for fast-moving, software-driven teams.
> ------------------------------
> How do I use ZenHub?
>
> To get set up with ZenHub, all you have to do is *download the browser
> extension <https://www.zenhub.io?utm_source=ZHOnboarding>* and log in
> with your GitHub account. Once you do, you’ll get access to ZenHub’s
> complete feature-set immediately.
> What can ZenHub do?
>
> ZenHub adds a series of enhancements directly inside the GitHub UI:
>
>    - Real-time, customizable task boards for GitHub issues;
>    - Multi-Repository burndown charts, estimates, and velocity tracking
>    based on GitHub Milestones;
>    - Personal to-do lists and task prioritization;
>    - Time-saving shortcuts – like a quick repo switcher, a “Move issue”
>    button, and much more.
>
> Add ZenHub to GitHub <https://www.zenhub.io?utm_source=ZHOnboarding>
>
> *Still curious? See more ZenHub features
> <https://www.zenhub.io/features?utm_source=ZHOnboarding> or read user
> reviews
> <https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd/reviews>.
> This issue was written by your friendly ZenHub bot, posted by request from
> @joeponcy <https://github.com/joeponcy>.*
>
> [image: ZenHub Board]
> <https://cloud.githubusercontent.com/assets/8771909/11153956/233ac4a8-89f1-11e5-94b1-1569d3f38b4d.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Innovate-Inc/EMEMetadataToolKit/issues/33>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACB0vCoeC6hsyueu9sp0_1-wf6i0WaDKks5qKZncgaJpZM4IzJLT>
> .
>



-- 
Torrin Hultgren
Senior Manager, Geospatial Solutions
Innovate!, Inc.
O:  (703) 922-9090 x737

http://www.innovateteam.com

Innovate!, Inc. is a Virginia-based 8(a), Hispanic- and woman-owned
business delivering Geospatial, Information Technology, Security,
Business Consulting, Project Management and Executive Coaching
solutions to our government and private sector clients.  Check us out
at www.innovateteam.com.

**Comment by joeponcy** [comment]
I'm multi-tasking.
