### ISSUE TITLE
Handle unbounded keyword field

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EMEMetadataToolKit#35]
Within ArcCatalog, the Item Description pane contains a tags field that is unrestricted by any Thesaurus and disconnected from all of the other keywords, yet this field is what is synchronized to ArcGIS Online. Suggest we find technical option to disable editing of this Tags field and make it autopopulated from bounded keyword selection options.

**Comment by dspinosa** [comment]
Which keywords list should we bind to tags?

**Comment by torrin47** [comment]
Ummm, can you be more specific?  Which what tags where?

**Comment by dspinosa** [comment]
See where this xpath is used and what happens if it is not populated. metadata/dataIdInfo/searchKeys/keyword

**Comment by joeponcy** [comment]
What did we decide for this issue?
![image](https://cloud.githubusercontent.com/assets/5324141/17417646/41f869ee-5a49-11e6-80e1-51b01dc049bc.png)

**Comment by joeponcy** [comment]
Create Custom Validator:
Error if Tags exist in metadata
Move Tags TextBox to new Error page

**Comment by joeponcy** [comment]
Validation error if tags exist.
Read only textbox
Button to copy textbox to clipboard
Button to clear tags textbox
