### ISSUE TITLE
User Keywords from EME3.2/EME4.x in ArcCatalog

### ISSUE THREAD

**Issue by joeponcy** [Innovate-Inc/EMEMetadataToolKit#39]
Do we want user keywords in the Arc Catalog Metadata Editor?

**Comment by torrin47** [comment]
Yeah, sure, users are welcome to add their own keywords in addition to any keywords we've specified as mandatory.

**Comment by joeponcy** [comment]
We need two XPath queries to check which keywords thesaurus is used and then pull corresponding keywords:
/metadata/dataIdInfo/themeKeys/thesaName/resTitle = "User"
/metadata/dataIdInfo/themeKeys/thesaName/resTitle = "EPA GIS Keyword Thesaurus"

**Comment by dspinosa** [comment]
Try these:
/metadata/dataIdInfo/themeKeys[thesaName/resTitle[contains(. , 'EPA GIS Keyword Thesaurus')]]/keyword
/metadata/dataIdInfo/themeKeys[thesaName/resTitle[contains(. , 'User')]]/keyword
