### ISSUE TITLE
Program Code needs to be added as a Keyword

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EMEMetadataToolKit#40]
EPA Guidance is here:

Field | Tags (Federal Program Code)
------------ | -------------
Required? | Always 
Guidance	| A program code is mandatory for all federal agencies. More information about the Federal Program Inventory is available here: https://www.performance.gov/sites/default/files/files/Federal_Program_Inventory_Fact_Sheet_.pdf and here: http://www.gao.gov/products/GAO-15-83
Accepted Values | http://goals.performance.gov/sites/default/files/images/FederalProgramInventory_FY13_MachineReadable_091613.xls
Example |	"015:001"
ArcCatalog Editor Location | Overview > Topics & Keywords > Subtopic Keywords > {Keywords subpage}
ArcGIS Metadata XPath |	/metadata/dataIdInfo/subTopicCatKeys/
Project Open Data Element | programCode
ISO 19115 | 
//gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:descriptiveKeywords/gmd:MD_Keywords/gmd:type/gmd:MD_KeywordTypeCode
FGDC CSDGM Element |	/metadata/idinfo/keywords/place/placekey

Guidance from FGDC:

Recommend hardcoding program information into the POD, if not feasible then add to keywords - locate program code in the Federal Program Inventory doc - add Program Code, e.g. "015:001" as a Theme Keyword - list ‘Federal Program Inventory’ as associated Theme Keyword Thesaurus

Keyword = <program code> + Thesaurus = Federal Program Inventory	
//gmd:identificationInfo/gmd:MD_DataIdentification/gmd:descriptiveKeywords/gmd:MD_Keywords/gmd:keyword (gco:CharacterString or gmx:Anchor) + //gmd:identificationInfo/gmd:MD_DataIdentification/gmd:descriptiveKeywords/gmd:MD_Keywords/gmd:thesaurusName/gmd:CI_Citation/gmd:title = 'Federal Program Inventory'

**Comment by joeponcy** [comment]
@torrin47 Can this field accept multiple program codes or just a single code per project?

**Comment by torrin47** [comment]
Per Project Open Data guidance, an array of codes is acceptable.  

Field #	programCode
Cardinality	(0,n)
Required	Yes, for United States Federal Government Agencies
Accepted Values	Array of strings
Usage Notes	Provide an array of programs related to this data asset, from the Federal Program Inventory.
Example	{"programCode":["015:001"]} or if multiple programs, {"programCode":["015:001","015:002"]}

That's not hard to accommodate in the XML, but I understand it adds to the UI complexity. That's why I was thinking checkboxes.  I can't think of any cases where EPA has actually chosen more than one, but it's been tough to do so in previous editors, so they might if given the tools to do so.
