### ISSUE TITLE
Enable 1-click operation for Language and country code

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EMEMetadataToolKit#42]
This goes hand-in-hand with other quick default elements, but it's a pretty big timesaver to be able to click a single button to populate Metadata Details with "English" and "United States", rather than having to scroll through the full list of countries.

**Comment by joeponcy** [comment]
Add if statement to check if markup exists. If not then populate with "English" and "United States". If it does exist, leave current values.
