### ISSUE TITLE
Empty Keywords Markup Nodes

### ISSUE THREAD

**Issue by joeponcy** [Innovate-Inc/EMEMetadataToolKit#54]
Current solution will create empty keyword nodes
Explore possible solutions that doesn't create empty nodes if thesaurus keywords don't exist.

**Comment by torrin47** [comment]
Appropriate to be thorough, but let's keep this a low priority issue, I'm not sure it's even necessary to be a part of an MVP.

**Comment by joeponcy** [comment]
I agree. Not needed for MVP
