### ISSUE TITLE
Add text to the Security Constraint Classification showing Domain Mapping (POD specification)

### ISSUE THREAD

**Issue by joeponcy** [Innovate-Inc/EMEMetadataToolKit#56]
![image](https://cloud.githubusercontent.com/assets/5324141/18972914/de90e498-864f-11e6-8ad2-cee75c30ef88.png)

**Comment by joeponcy** [comment]
add "data.gov:" to domain label

**Comment by torrin47** [comment]
Did this not make it into the latest install package?  It looked great in the webinar, but I'm not seeing it in my installation.

**Comment by joeponcy** [comment]
It should be in the installer I sent to you…

Or, I think the domain mapping is in the legal constraints. Should security constraints have the mapping too?

Sent from my Windows 10 phone

**Comment by torrin47** [comment]
Legal constraints was the EPA license, security constraints was public/nonpublic/restrictedpublic and the CUI codes.

**Comment by joeponcy** [comment]
Yeah, I see that now. I'll fix that before release too.

**Comment by joeponcy** [comment]
Do those same domains apply to the legal constraints classifications as well?

**Comment by torrin47** [comment]
No, not really - at least, that's not where we'd be looking for the official data.gov security classification, even though the same list is available. Best to only put the mapping in the place where it matters.

**Comment by joeponcy** [comment]
The part that confuses me is "“_**restricted public**_” when resource constraints code is copyright, patent, patentPending, trademark, license, or intellectualPropertyRights" 
None of that applies to Classification Code.

**Comment by joeponcy** [comment]
What is the domain mapping for "**_Sensitive_**" and "**_Official Use Only_**"?

![image](https://cloud.githubusercontent.com/assets/5324141/22030136/956fb3aa-dc91-11e6-8618-7f8f8598e40d.png)

**Comment by joeponcy** [comment]
It seems like Legal Constraints has more options that require domain mapping. What are your thoughts?

![image](https://cloud.githubusercontent.com/assets/5324141/22030289/055badf4-dc92-11e6-9a01-ea6e93db0bdc.png)

**Comment by torrin47** [comment]
Whoa there!  No data.gov mappings for legal constraints.  Security constraints only.  And I would have said  "restricted" corresponds to "restricted public" not non-public.  Restricted and Official Use Only would be the two "restricted public" items, Unclassified would be the single "public" choice, and the rest would be non-public.

**Comment by joeponcy** [comment]
I would also say that "restricted" should correspond with "restricted-public", but the tech spec says:

“non-public” when resource constraints code is restricted, confidential, secret, or topSecret

**Comment by joeponcy** [comment]
Does this look right?

![image](https://cloud.githubusercontent.com/assets/5324141/22034383/f974c4da-dca0-11e6-8bfc-4e18fa81b76e.png)

**Comment by joeponcy** [comment]
and this...

![image](https://cloud.githubusercontent.com/assets/5324141/22034438/263274c2-dca1-11e6-85a5-0778e04798a6.png)

**Comment by joeponcy** [comment]
This section may need to be revised to better fit what is displayed in ArcMap:

> Project Open Data ISO field-mapping: “**non-public**” when resource constraints code is _restricted, confidential, secret, or topSecret_ and “**restricted public**” when resource constraints code is _copyright, patent, patentPending, trademark, license, or intellectualPropertyRights_...

https://www.epa.gov/geospatial/epa-metadata-technical-specification#access-level

**Comment by torrin47** [comment]
Fragnamnit, you're right. That language is taken straight from the page below, but we don't have the ability within the EDG to check both places and determine an access code based on multiple fields. So we're going to have to clean up the tech spec to remove mention of any Legal Constraints options and make it entirely based on security constraints. Which leaves us short on options we can consider "restricted public". I'm going to unilaterally say the field "restricted" should map to "restricted public" as the most straightforward and intuitive option. 

https://project-open-data.cio.gov/v1.1/metadata-resources/#field-mappings
accessLevel	Public Access Level	required	no	default value is “public”	

1. resource constraints with codes of restricted, confidential, secret, or topSecret 
2. resource constraints with codes of copyright, patent, patentPending, trademark, license, or intellectualPropertyRights
3. ISO codes do not specify ‘public’ as a constraint code	

1. “non-public” when 
a. //gmd:identificationInfo/gmd:MD_DataIdentification/gmd:resourceConstraints/gmd:MD_LegalConstraints/gmd:accessConstraints/gmd:MD_RestrictionCode == restricted
b. //gmd:identificationInfo/gmd:MD_DataIdentification/gmd:resourceConstraints/gmd:MD_SecurityConstraints/gmd:classification/gmd:MD_ClassificationCode == restricted, confidential, secret, or topSecret
2. “restricted public” when //gmd:identificationInfo/gmd:MD_DataIdentification/gmd:resourceConstraints/gmd:MD_LegalConstraints/gmd:accessConstraints/gmd:MD_RestrictionCode == copyright, patent, patentPending, trademark, license, or intellectualPropertyRights
3. set value of POD json field to public if these values do not exist in metadata
