### ISSUE TITLE
Create model builder script for upgrade process to remove legacy tags.

### ISSUE THREAD

**Issue by joeponcy** [Innovate-Inc/EMEMetadataToolKit#60]

**Comment by dspinosa** [comment]
#8

**Comment by torrin47** [comment]
It's not polished with documentation, and I haven't checked out relative paths, but the XSLT works (the important part) and in theory it performs the whole upgrade, and could even work fine on already upgraded docs.  

[EPAUpgradeToolbox.zip](https://github.com/Innovate-Inc/EMEMetadataToolKit/files/570342/EPAUpgradeToolbox.zip)

**Comment by torrin47** [comment]
Ok, did a lot more testing - the first script did an in-place upgrade of the metadata, which is fine in some circumstances, but if it's already been through an upgrade, not so nice things can happen. So safer to make a copy, upgrade that, and then do the extra cleanup. Also, for some reason the toolbox tool wasn't working as a batch process - all the outputs were identical - so I converted it to a Python Toolbox. Works more consistently.  
[EPAUpgradeMetadata.zip](https://github.com/Innovate-Inc/EMEMetadataToolKit/files/581806/EPAUpgradeMetadata.zip)

**Comment by joeponcy** [comment]
Add to installer. Should be installed to: \AppData\Roaming\ESRI\Desktop10.4\ArcToolbox\My Toolboxes

**Comment by joeponcy** [comment]
See Issue #81
