### ISSUE TITLE
Create Wiki with links to installers

### ISSUE THREAD

**Issue by joeponcy** [Innovate-Inc/EMEMetadataToolKit#66]
Where do we want to host the binaries?

**Comment by torrin47** [comment]
I don't see a downside to simply uploading the binaries to GitHub - as long as they're under certain limits, they can just be posted right to a wiki page, right?

**Comment by torrin47** [comment]
Right, files can be attached to issues, but not wikis. But that leaves a giant loophole.  
[emetoolkit_10.4x_installer.msi.zip](https://github.com/Innovate-Inc/EMEMetadataToolKit/files/590779/emetoolkit_10.4x_installer.msi.zip)

**Comment by joeponcy** [comment]
Fixes Issue #69 
Please uninstall any previous version before running this installer.
[emetoolkit_10.4x_installer-0.9.8.zip](https://github.com/Innovate-Inc/EMEMetadataToolKit/files/596161/emetoolkit_10.4x_installer-0.9.8.zip)

**Comment by joeponcy** [comment]
Fix for Issue #69
[emetoolkit_10.4x_installer-0.9.8.zip](https://github.com/Innovate-Inc/EMEMetadataToolKit/files/596210/emetoolkit_10.4x_installer-0.9.8.zip)
