### ISSUE TITLE
Make a .NET 3.5 compatible installer 

### ISSUE THREAD

**Issue by joeponcy** [Innovate-Inc/EMEMetadataToolKit#67]
ArcGIS 10.3 and below uses .NET 3x and crashes if trying to use the toolkit built with .NET 4x

**Comment by torrin47** [comment]
[emetoolkit_10.3x_installer.msi.zip](https://github.com/Innovate-Inc/EMEMetadataToolKit/files/592746/emetoolkit_10.3x_installer.msi.zip)

**Comment by joeponcy** [comment]
Fix Issue#69
[emetoolkit_10.3x_installer-0.9.8.zip](https://github.com/Innovate-Inc/EMEMetadataToolKit/files/596179/emetoolkit_10.3x_installer-0.9.8.zip)
