### ISSUE TITLE
Keyword List Inconsistent in Spacing on 10.3

### ISSUE THREAD

**Issue by dspinosa** [Innovate-Inc/EMEMetadataToolKit#70]
At least on my version of 10.3 the list boxes are a bit inconsistent between the topic cats, key words, and Program Code
![image](https://cloud.githubusercontent.com/assets/5093530/20372330/364b0fde-ac1f-11e6-8e41-e4e266e23caf.png)

**Comment by joeponcy** [comment]
Yep, definitely an issue. Just verified the same on my 10.3 install.
