### ISSUE TITLE
Create Add-In with 3x & 4x tools

### ISSUE THREAD

**Issue by joeponcy** [Innovate-Inc/EMEMetadataToolKit#76]
![image](https://cloud.githubusercontent.com/assets/5324141/20810468/b612dc42-b7be-11e6-926a-e976895a291c.png)

**Comment by dspinosa** [comment]
Bulk editing tool?

**Comment by torrin47** [comment]
This issue was moved to USEPA/EPA-Metadata-Editor-5#11

**Comment by joeponcy** [comment]
Issue transferred to the [USEPA Repo](https://github.com/USEPA/EPA-Metadata-Editor-5) using https://github.com/google/github-issue-mover.
