### ISSUE TITLE
Investigate ArcGIS Upgrade Button and what happens with UUID 

### ISSUE THREAD

**Issue by dspinosa** [Innovate-Inc/EMEMetadataToolKit#8]
What happens to UUIDs in CSDG that get upgraded to ArcGIS

**Comment by torrin47** [comment]
Holy moly, just stumbled across this toolkit - I know the Metadata Toolkit codebase is WPF, but it's possible that some of the XML manipulation might be easier with Python?
https://github.com/Esri/hermes

**Comment by torrin47** [comment]
Ok, I just ran the test, and it appears that the legacy UUID survives the upgrade, but does not make it to the location we need it to be in.  It remains at /metadata/Esri/PublishedDocID.  That should make it easier for us - the first time someone opens our tool, if /metadata/mdFileID is empty, we can check for the existence of /metadata/Esri/PublishedDocID and copy the value over. Or is there any need to preserve the UUID at the old xpath? Now that I think it through, leaving it there just adds an additional burden to us to keep the values synchronized to prevent confusion when the legacy xpath is ignored going forward. Might be better to purge the old xpath value after the UUID has been copied over.

**Comment by joeponcy** [comment]
This issue may be addressed with a separate update tool/script

**Comment by joeponcy** [comment]
This will be part of the upgrade tool. Issue #60
