### ISSUE TITLE
Add model builder script to installer.

### ISSUE THREAD

**Issue by joeponcy** [Innovate-Inc/EMEMetadataToolKit#81]
#60 

- [x] Add model builder script to repo.
- [ ] Add to installer. Should be installed to: \AppData\Roaming\ESRI\Desktop10.4\ArcToolbox\My Toolboxes

**Comment by torrin47** [comment]
Updated XSLT to move "purpose" to "supplementary info" and change timeinstants to timeextents and slightly improve errorhandling.  Haven't added additional tools yet, can potentially do that after it's in the repo.
[EPAUpgradeFGDC2ArcGIS.zip](https://github.com/Innovate-Inc/EMEMetadataToolKit/files/631987/EPAUpgradeFGDC2ArcGIS.zip)
