### ISSUE TITLE
Add dates to keyword citations

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EMEMetadataToolKit#89]
I think we should be able to save users from having to populate the thesaurus publication dates, right?  I'd like to address these in the upgrade process - 

- [x] ISO 19115 Topic Category - could probably come up with a complete citation here, dating back to ISO 2003   or NAP
- [x] EPA GIS Keyword Thesaurus - dates back to 2007 metadata tech spec, no meaningful update with new spec.
- [x] Place keywords - probably also dates back to 2007 tech spec.  
- [x] User keywords - do we want to automatically populate the upgrade date, or leave this for the user to populate?

**Comment by joeponcy** [comment]
Add user thesaurus xml & epa thesaurus xml docs to repo.

**Comment by torrin47** [comment]
Here are the completed thesaurus citations in ArcGIS Format, please let me know if a different format would be more helpful:

`        <placeKeys xmlns="">
            <thesaName xmlns="">
                <resTitle>EPA Place Names</resTitle>
                <date>
                    <pubDate>2015-01-31</pubDate>
                </date>
                <citOnlineRes xmlns="">
                    <linkage>https://ofmpub.epa.gov/sor_internet/registry/termreg/searchandretrieve/taxonomies/search.do?search=&amp;searchString=&amp;taxonomyName=WBT%20-%20Geographic%20Locations</linkage>
                    <orFunct>
                        <OnFunctCd value="002"/>
                    </orFunct>
                    <orName>Web Taxonomy - Geographic Locations</orName>
                </citOnlineRes>
            </thesaName>
            <thesaLang>
                <languageCode value="eng"/>
                <countryCode value="US"/>
            </thesaLang>
            <keyword>United States</keyword>
        </placeKeys>
        <themeKeys xmlns="">
            <thesaLang>
                <languageCode value="eng"/>
                <countryCode value="US"/>
            </thesaLang>
            <thesaName xmlns="">
                <resTitle>EPA GIS Keyword Thesaurus</resTitle>
                <date>
                    <pubDate>2007-11-02</pubDate>
                </date>
                <citOnlineRes xmlns="">
                    <linkage>https://www.epa.gov/geospatial/epa-metadata-technical-specification</linkage>
                    <orName>EPA Metadata Technical Specification</orName>
                    <orFunct>
                        <OnFunctCd value="002"/>
                    </orFunct>
                </citOnlineRes>
            </thesaName>
            <keyword>Environment</keyword>
        </themeKeys>
        <themeKeys xmlns="">
            <thesaLang>
                <languageCode value="eng"/>
                <countryCode value="US"/>
            </thesaLang>
            <thesaName xmlns="">
                <resTitle>Federal Program Inventory</resTitle>
                <date>
                    <pubDate>2013-09-16</pubDate>
                </date>
                <citOnlineRes xmlns="">
                    <linkage>https://www.performance.gov/federalprograminventory</linkage>
                    <orFunct>
                        <OnFunctCd value="002"/>
                    </orFunct>
                    <orName>Federal Program Inventory</orName>
                </citOnlineRes>
            </thesaName>
            <keyword>020:072</keyword>
        </themeKeys>`

**Comment by joeponcy** [comment]
This is great. Thanks Torrin!
