### ISSUE TITLE
On Metadata Details page, highlight only mandatory elements

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EMEMetadataToolKit#92]
The current shading makes it look like Parent Identifier, Dataset URI, and Function are all mandatory, which is not the case.  Only Datestamp and File Identifier are.  Can we highlight only these items?

![image](https://cloud.githubusercontent.com/assets/2127036/21374017/6ad2c78c-c6f1-11e6-9737-44b3a1e73c17.png)

**Comment by joeponcy** [comment]
We can, but I think we all agreed that it didn't look as nice as highlighting the entire section to indicate that there are mandatory elements in that section. The validation errors at the top help to further narrow it down for the end user.
