### ISSUE TITLE
Shading on resource extents is confusing

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EMEMetadataToolKit#93]
This might just be a topic for discussion, but it's making it seem as if a bounding box and temporal extent are mandatory in every new extent section.  Can we think through how we might indicate that only one of each is mandatory? This gets to the challenge of shading when many elements can potentially be added. Do we hard code one bounding box and one temporal extent that don't have "+ New" elements in the interface and shade them and then not shade new ones?

**Comment by joeponcy** [comment]
I do like the idea of reworking this page. I agree that it is a bit confusing and looks kinda messy.
